version: "3.9"

services:
  jingen:
    image: ghcr.io/devopsgroupeu/jingen:latest
    container_name: jingen
    volumes:
      - ~/my-local-templates:/templates
      - ~/data:/data
      - ./output:/output
    command: >
      --input-dir /templates
      --output-dir /output
      --data-files /data/00_base.yaml /data/10_override.yaml
